
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./glob.css";
import Navbar from "@/components/navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { Sidebar } from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Memories Gallery",
  description: "Generated by Syeda Hafsa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      
      <html lang="en">
        <body className={inter.className}>
          {/* <main className="max-w-6xl mx-auto"> */}
          {/* <Navbar /> */}
        <div className="flex">
<div><Sidebar/></div>
<div> {children}</div>
</div>
         
{/*          
<div className="w-full">             
</div>       */}
          {/* </main> */}
        </body>
      </html>
    
  );
}